"""
title: Azure DevOps
author: AzureMCP
version: %%VERSION%%
description: Azure DevOps Server tools backed by the AzureMCP server, started on demand with the calling user's own PAT. Toolsets: %%TOOLSETS%%.
"""

# Generated by tools/OpenWebUiPluginGenerator. Do not edit by hand; regenerate instead.

import asyncio
import hashlib
import os
import stat
from pathlib import Path
from typing import Optional

import anyio
import httpx
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from pydantic import BaseModel, Field

try:
    from open_webui.config import CACHE_DIR

    _CACHE_ROOT = Path(CACHE_DIR) / "tools" / "azure_devops" / "server"
except ImportError:
    _CACHE_ROOT = Path("/tmp") / "azure_devops" / "server"

_BINARY_NAME = "AzureDevOpsServer.Mcp"
_download_lock = asyncio.Lock()


class Tools:
    class Valves(BaseModel):
        collection_url: str = Field(
            default="",
            description="Azure DevOps Server collection URL, e.g. https://devops.example.local/DefaultCollection.",
        )
        server_download_url: str = Field(
            default=%%DOWNLOAD_URL%%,
            description="URL of the AzureMCP self-contained linux-x64 server binary.",
        )
        server_sha256: str = Field(
            default=%%SHA256%%,
            description="Expected SHA-256 of that binary. A download that does not match is rejected.",
        )
        default_project: str = Field(
            default="",
            description="Optional project used when a call does not name one.",
        )
        timeout_seconds: int = Field(
            default=60,
            description="Maximum duration of one tool call, including server start.",
        )

    class UserValves(BaseModel):
        ado_pat: str = Field(
            default="",
            description="Your personal Azure DevOps PAT. Only you can see or change it.",
            json_schema_extra={"input": {"type": "password"}},
        )

    def __init__(self):
        self.valves = self.Valves()

%%TOOL_METHODS%%

    async def _call_tool(self, name: str, arguments: dict, user: dict) -> str:
        valves = user.get("valves")
        pat = getattr(valves, "ado_pat", "") if valves is not None else ""
        if not pat:
            return (
                "Your Azure DevOps PAT is not set. In the chat, open Integrations, go to Tools, "
                "and use the settings icon next to Azure DevOps to add it."
            )
        if not self.valves.collection_url:
            return "The Azure DevOps tool is not configured: an administrator must set the collection URL."

        try:
            server = await self._ensure_server()
        except Exception as error:
            return f"The Azure DevOps server could not be prepared: {_describe(error)}"

        # The MCP stdio client passes only HOME and PATH plus these, never Open WebUI's own environment.
        env = {"ADOS_COLLECTION_URL": self.valves.collection_url, "ADOS_PAT": pat}
        if self.valves.default_project:
            env["ADOS_DEFAULT_PROJECT"] = self.valves.default_project

        arguments = {key: value for key, value in arguments.items() if value is not None}
        try:
            with anyio.fail_after(self.valves.timeout_seconds):
                parameters = StdioServerParameters(command=str(server), args=[], env=env)
                async with stdio_client(parameters) as (read, write):
                    async with ClientSession(read, write) as session:
                        await session.initialize()
                        result = await session.call_tool(name, arguments)
        except TimeoutError:
            return f"Azure DevOps did not answer within {self.valves.timeout_seconds} seconds."
        except Exception as error:
            return f"The Azure DevOps server failed: {_describe(error)}"

        text = "\n".join(block.text for block in result.content if getattr(block, "text", None))
        return f"Azure DevOps returned an error: {text}" if result.isError else text

    async def _ensure_server(self) -> Path:
        expected = self.valves.server_sha256.strip().lower()
        if not self.valves.server_download_url or len(expected) != 64:
            raise RuntimeError("an administrator must set the server download URL and its SHA-256")

        target = _CACHE_ROOT / expected / _BINARY_NAME
        if target.is_file():
            return target

        async with _download_lock:
            if target.is_file():
                return target

            target.parent.mkdir(parents=True, exist_ok=True)
            partial = target.with_name(_BINARY_NAME + ".partial")
            digest = hashlib.sha256()
            async with httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
                async with client.stream("GET", self.valves.server_download_url) as response:
                    response.raise_for_status()
                    with open(partial, "wb") as file:
                        async for chunk in response.aiter_bytes():
                            digest.update(chunk)
                            file.write(chunk)

            if digest.hexdigest() != expected:
                partial.unlink(missing_ok=True)
                raise RuntimeError("the downloaded server does not match the configured SHA-256")

            os.chmod(partial, os.stat(partial).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            os.replace(partial, target)

        return target


def _describe(error: BaseException) -> str:
    while isinstance(error, BaseExceptionGroup) and error.exceptions:
        error = error.exceptions[0]
    message = str(error)[:300]
    return f"{type(error).__name__}: {message}" if message else type(error).__name__
