"""
title: Azure DevOps
author: AzureMCP
version: %%VERSION%%
description: Azure DevOps Server tools backed by the AzureMCP server, started on demand with the calling user's own PAT. Toolsets: %%TOOLSETS%%.
"""

# Generated by tools/OpenWebUiPluginGenerator. Do not edit by hand; regenerate instead.

import asyncio
import hashlib
import json
import os
import re
import stat
import tempfile
from pathlib import Path
from typing import Optional

import anyio
import httpx
from anyio import to_thread
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from open_webui.config import CACHE_DIR
from pydantic import BaseModel, Field

_CACHE_ROOT = Path(CACHE_DIR) / "tools" / "azure_devops" / "server"
_BINARY_NAME = "AzureDevOpsServer.Mcp"
_SYSTEM_CA_BUNDLES = (
    Path("/etc/ssl/certs/ca-certificates.crt"),  # Debian, Ubuntu, Alpine
    Path("/etc/pki/tls/certs/ca-bundle.crt"),  # Red Hat, Fedora
    Path("/etc/ssl/ca-bundle.pem"),  # SUSE
    Path("/etc/ssl/cert.pem"),  # Alpine, BSD
)
_SHA256 = re.compile(r"[0-9a-f]{64}")
_MAX_SERVER_BYTES = 256 * 1024 * 1024
_DOWNLOAD_TIMEOUT_SECONDS = 600
_download_lock = asyncio.Lock()
_verified_servers: set[str] = set()


class Tools:
    class Valves(BaseModel):
        collection_url: str = Field(
            default="",
            description="Azure DevOps Server collection URL, e.g. https://devops.example.local/DefaultCollection.",
        )
        server_download_url: str = Field(
            default=%%DOWNLOAD_URL%%,
            description="URL of the AzureMCP self-contained linux-x64 server binary.",
        )
        server_sha256: str = Field(
            default=%%SHA256%%,
            description="Expected SHA-256 of that binary. A download that does not match is rejected.",
        )
        default_project: str = Field(
            default="",
            description="Optional project used when a call does not name one.",
        )
        ca_certificate: str = Field(
            default="",
            description="PEM certificate of the internal authority that signed the Azure DevOps Server certificate. Leave empty when the chain is already trusted.",
        )
        timeout_seconds: int = Field(
            default=60,
            gt=0,
            description="Maximum duration of one tool call, including starting the server. The first-use download of the server is limited separately to 10 minutes.",
        )

    class UserValves(BaseModel):
        ado_pat: str = Field(
            default="",
            description="Your personal Azure DevOps PAT. Only you can see or change it.",
            json_schema_extra={"input": {"type": "password"}},
        )

    def __init__(self):
        self.valves = self.Valves()

%%TOOL_METHODS%%

    async def _call_tool(self, name: str, arguments: dict, user: dict) -> str:
        valves = user.get("valves")
        pat = getattr(valves, "ado_pat", "") if valves is not None else ""
        if not pat:
            return (
                "Your Azure DevOps PAT is not set. In the chat, open Integrations, go to Tools, "
                "and use the settings icon next to Azure DevOps to add it."
            )
        if not self.valves.collection_url:
            return "The Azure DevOps tool is not configured: an administrator must set the collection URL."

        # A slow first download must not eat the per-call timeout, or it would be cancelled and retried forever.
        try:
            with anyio.fail_after(_DOWNLOAD_TIMEOUT_SECONDS):
                server = await self._ensure_server()
            trust_bundle = self._trust_bundle()
        except TimeoutError:
            return f"The Azure DevOps server could not be downloaded within {_DOWNLOAD_TIMEOUT_SECONDS} seconds."
        except Exception as error:
            return f"The Azure DevOps server could not be prepared: {_describe(error)}"

        # Only HOME and PATH are inherited; Open WebUI's own environment and its secrets never reach the server.
        env = {key: os.environ[key] for key in ("HOME", "PATH") if key in os.environ}
        env["ADOS_COLLECTION_URL"] = self.valves.collection_url
        env["ADOS_PAT"] = pat
        if trust_bundle is not None:
            env["SSL_CERT_FILE"] = str(trust_bundle)
        if self.valves.default_project:
            env["ADOS_DEFAULT_PROJECT"] = self.valves.default_project

        arguments = {key: value for key, value in arguments.items() if value is not None}
        try:
            with anyio.fail_after(self.valves.timeout_seconds):
                parameters = StdioServerParameters(command=str(server), args=[], env=env)
                async with stdio_client(parameters) as (read, write):
                    async with ClientSession(read, write) as session:
                        await session.initialize()
                        result = await session.call_tool(name, arguments)
        except TimeoutError:
            return f"Azure DevOps did not answer within {self.valves.timeout_seconds} seconds."
        except Exception as error:
            return f"The Azure DevOps server failed: {_describe(error)}"

        text = "\n".join(block.text for block in result.content if getattr(block, "text", None))
        if not text and result.structuredContent is not None:
            text = json.dumps(result.structuredContent, ensure_ascii=False)
        return f"Azure DevOps returned an error: {text}" if result.isError else text

    def _trust_bundle(self) -> Path | None:
        certificate = self.valves.ca_certificate.strip()
        if not certificate:
            return None

        bundle = _CACHE_ROOT.parent / "trust" / f"{hashlib.sha256(certificate.encode()).hexdigest()}.pem"
        if _is_present(bundle):
            return bundle

        # SSL_CERT_FILE replaces the trust store outright, so the bundle must carry the system roots as well.
        # Without them the server would trust only the configured authority, which is worse than not helping at all.
        source = next((path for path in _SYSTEM_CA_BUNDLES if path.is_file()), None)
        if source is None:
            raise RuntimeError(
                "no system certificate bundle was found, so trusting the configured authority "
                "would leave the server without any public root certificate"
            )

        _prepare_directory(bundle.parent)
        system_roots = source.read_text(encoding="utf-8")
        # Written aside and renamed, so an interrupted write can never leave a half-built bundle in place.
        descriptor, temporary = tempfile.mkstemp(dir=bundle.parent, prefix=f"{bundle.stem}.", suffix=".partial")
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as file:
                file.write(f"{system_roots}\n{certificate}\n")
            os.replace(temporary, bundle)
        except BaseException:
            Path(temporary).unlink(missing_ok=True)
            raise

        return bundle

    async def _ensure_server(self) -> Path:
        expected = self.valves.server_sha256.strip().lower()
        # The checksum becomes a directory name, so anything but 64 hex characters could escape the cache.
        if not self.valves.server_download_url or not _SHA256.fullmatch(expected):
            raise RuntimeError(
                "an administrator must set the server download URL and its SHA-256 as 64 hexadecimal characters"
            )

        target = _CACHE_ROOT / expected / _BINARY_NAME
        if expected in _verified_servers and _is_present(target):
            return target

        async with _download_lock:
            if not (expected in _verified_servers and _is_present(target)):
                _verified_servers.discard(expected)
                _prepare_directory(target.parent)
                # A cached file is trusted only once its hash is checked in this process; anything else is replaced.
                if not await _matches(target, expected):
                    target.unlink(missing_ok=True)
                    await self._download(target, expected)
                _verified_servers.add(expected)

        return target

    async def _download(self, target: Path, expected: str) -> None:
        partial = target.with_name(_BINARY_NAME + ".partial")
        digest = hashlib.sha256()
        received = 0
        try:
            async with httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
                async with client.stream("GET", self.valves.server_download_url) as response:
                    response.raise_for_status()
                    # The checksum is only known once the download ends, so the size is what stops a runaway one.
                    declared = int(response.headers.get("content-length") or 0)
                    if declared > _MAX_SERVER_BYTES:
                        raise RuntimeError(
                            f"the server download is {declared} bytes, over the {_MAX_SERVER_BYTES} byte limit"
                        )
                    # Always a brand-new file: whatever sits at this path, including a symlink, is removed first.
                    partial.unlink(missing_ok=True)
                    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
                    with os.fdopen(os.open(partial, flags, 0o600), "wb") as file:
                        async for chunk in response.aiter_bytes():
                            received += len(chunk)
                            if received > _MAX_SERVER_BYTES:
                                raise RuntimeError(f"the server download exceeded the {_MAX_SERVER_BYTES} byte limit")
                            digest.update(chunk)
                            file.write(chunk)
        except BaseException:
            partial.unlink(missing_ok=True)
            raise

        if digest.hexdigest() != expected:
            partial.unlink(missing_ok=True)
            raise RuntimeError("the downloaded server does not match the configured SHA-256")

        os.chmod(partial, stat.S_IRWXU)
        os.replace(partial, target)


def _prepare_directory(directory: Path) -> None:
    # Every component below Open WebUI's cache is created here and must not be a link that leads elsewhere.
    current = Path(CACHE_DIR)
    for part in directory.relative_to(current).parts:
        current = current / part
        if current.is_symlink():
            raise RuntimeError(f"refusing to use {current}: it is a symbolic link")
        current.mkdir(mode=0o700, exist_ok=True)


def _is_present(path: Path) -> bool:
    return path.is_file() and not path.is_symlink()


async def _matches(path: Path, expected: str) -> bool:
    if not _is_present(path):
        return False
    return await to_thread.run_sync(_sha256_of, path) == expected


def _sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _describe(error: BaseException) -> str:
    while isinstance(error, BaseExceptionGroup) and error.exceptions:
        error = error.exceptions[0]
    message = str(error)[:300]
    return f"{type(error).__name__}: {message}" if message else type(error).__name__
